### ISSUE TITLE
Should we rename our repo to arcus.azureml?

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.azureml#12]
In order to align with other repos, I'm wondering if we should rename this one to arcus.ml?

**Comment by tomkerkhove** [comment]
Thoughts @SamVanhoutte ?

**Comment by SamVanhoutte** [comment]
@tomkerkhove , since this repo & package is specifically for __Azure__ Machine Learning , I would keep it this way.  There can always be a arcus.ml (or arcus.machinelearning), in case we want to have generic, non-azure, specific things (which is perfectly possible)

**Comment by tomkerkhove** [comment]
Makes perfect sense to me!
