### ISSUE TITLE
The documentation web page has Invalid certificate

### ISSUE THREAD

**Issue by Dietatko** [arcus-azure/arcus.azureml#154]
**Describe the bug**
The website https://azure-ml.arcus-azure.net has invalid certificate. The common name is `*.netlify.app`.

**To Reproduce**
View https://azure-ml.arcus-azure.net

**Expected behavior**
Page has trusted certificate.

**Additional context**

**Comment by stijnmoreels** [comment]
Thanks for mentioning! We look into this.

**Comment by stijnmoreels** [comment]
This is fixed!
