### ISSUE TITLE
Initialize unified working folder structure

### ISSUE THREAD

**Issue by SamVanhoutte** [arcus-azure/arcus.azureml#30]
Provide a standard function that generates a unified working folder structure for a machine learning experiment.

Suggestion so far 

- Config
- Notebook
- Data
- Script
- Output
  - Model
  - Script

**Comment by SamVanhoutte** [comment]
@SriramAvatar : need your input on the folder structure - anything missing?

**Comment by SriramAvatar** [comment]
@SamVanhoutte , Script on the root level is not needed when we have Output/Script. Should we have all lower casing?

**Comment by SamVanhoutte** [comment]
@SriramAvatar  - was thinking about the output folder as the thing that gets automatically stored & persisted in the Run details on AzureML (while the root folder is probably not persisted necessarily, no?)

lower casing = yes, I think so

**Comment by SriramAvatar** [comment]
@SamVanhoutte , was thinking the script as raw python version of the notebook, that would be used in builds later. If we are trying to snapshot the code, then for the dev its easier with the notebook.
